# Generated by Django 4.1.dev20220304005948 on 2022-03-04 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mealSheetApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=mealSheetApi.models.path_and_rename)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mealSheetApi.unit')),
                ('kcal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('proteins', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealSheetApi.meal')),
            ],
        ),
    ]
