# Generated by Django 4.0.3 on 2022-03-16 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mealSheetApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealTime',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('coffee', 'coffee'), ('dinner', 'dinner'), ('snack', 'snack')], default='lunch', max_length=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='mealTimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
